dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=rs-collector
  - secure: S2QBfk4iIpztHX5L32YR/iP8Ar7drx8hwRCz7G+1aR2jUl4qyzE5JASSjEcuaIk4Wa5eU3Spm79PTmQqW4BhUZnEhZKqE214jXB7e5ay/X0YximqoB0TJjoXNhkqvI0u+EUiSPRdxQXKNWL6DVhyMvIObeooR1TsEA6Dak3ZIJwyfoTgTbz6YiqD+CsaX7ko+uUQfbHdsxbRpLozc5W75F2vgMKTZaQ4h289wT2NwTIk2t8UDlqojzwje26JbwyZzIWRQkfKaJyuY9HXeV9Mz4IVDnv13+ojroMzImEJqKoyl+Dfbll9L5ctYcxOXc+RnFHdNaeiiNQlYD5P3YZzQImwlLvw5pbudeWVRn2enozKHa6SGn9uBIjat5kTSBw+GZw01YCSX4wI+iGWGA5KLcdQMtqvsuQ5Q7eNgt7ui9Shc4s59GIzhVio6zhyb/PdIJGPiRc0BPZfNyfedd6rAS8D7dwE8FYDnlBxE/bpiyqdlgY+j2VWpW+LPtROuNklYrU5ALUGN1uYfN6tSLCxo5MIJMQasUkrVZHJ662cAAPRq9hRsYWIt8EfVQO0M7JsCSCSJqrU1H0zE7u5Cd7/Sxp2rMmwc3ASAo2kzsvcfwdMJC3/QzvDi1BJoXyPNTOiJudN81+JldGkW/qjDh17TCgCVCAu4wjHIqllvPS39eU=
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu DEPLOY_ARCH=amd64
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=armv7-unknown-linux-gnueabihf DEPLOY_ARCH=armhf
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: beta
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  allow_failures:
  - rust: beta
  - rust: nightly
branches:
  only:
  - master
  - travis-ci
  - "/^v.*$/"
before_install: set -e
install:
- sh .ci/install.sh
- source ~/.cargo/env || true
script:
- bash .ci/script.sh
after_script: set +e
before_deploy:
- sh .ci/before_deploy.sh
deploy:
  matrix:
  - provider: packagecloud
    username: lukaspustina
    token:
      secure: fCA7NaBLHi/jy73rdvw6Jz1fdKtQhp8o9l3pwLHnRdhFyqzgSxBK/hXtShjPhHUSKM1Crjk2CYIhOaA5tVN2lXflQxjaDkSDgW4MeiIIpPr2CR240SmGh/+U5DQ1UKN2+z0oxfohvteIAgMfcvZgl6ex4rPSGarw3L3/9VHMI7iS+ShotxnA9dbw0IZsmBMejYDY1xHYVqCHN60Yd/C1SlDAMJD2z0+bLRn1fR3dc9Gxj2bDzLK7vzAe7ORDnw+AHYB/9oUGMu94UCEQhJa4MFcngHwXEswH6jL6aDkQBzD5ZwcJ7WDNDWHJa67KayEwIorBjiszd2g7Bnf4xpObFdhkOJbSyt3gdyT7k3Ljb79HowAb5ySCI85YMZLb7TayBBF9zSEl2X0S3F/BovlHuXGehFUKxwSwLCtworShm90VJLN2hxpuYoPXBi3h8kyjZX5cBrUahqxI8Gp4eHfJ7Z9MlrErJq0HecrhujNM40w4baTwTch6t3h/PuTf0+6wKzXSY46pWN7SAjQcCWYCTEIFwUdr4RVe/pe7vLetuRJ1cc/ClSv2PxQF4cDHlwVD6SLXLU3jLiGmzHisZU0NBqvqZVCkpbDnF31/PlpMfY0aikXF3oA+XeSmicWR8bLlsAPTlf1NdCu+aJwIpaOVRLPmKEBVygDBjaX5l2tf/V0=
    repository: opensource
    dist: ubuntu/trusty
    package_glob: "**/*.deb"
    skip_cleanup: true
    on:
      tags: true
      condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$DEPLOY_ARCH"
  - provider: releases
    api_key:
      secure: DGYtB0LUYX6YROgbbvyEMSZTNjF+HPJOWQE2trnat0vRfLyGfKtNPLcXFUgAUwzJ4fIBCbsXkwY94b50BEMYMhcIQIyXhkN7AzZ0Tv+tnN281QW8Ma+2ZXP3vug23v9S6ZtpuXVVSqFuJjAV92TSHO/BoWAGUlK6O3OgJlZ9i4u/venkz1fnUVTgmLsKaNVqyLKKlvkPe/T/CjH3P73b668U3Y9X4IiWLm9adJAhgGutWf+cRpRxRcnY9bh+GcpYq0MoR9FQIWREFtYty3OQZCnsc2FbPKfNm6dkgPzSe01O5Zenf+EfpC1wizEfrL4378a/BDF9F0jSjtIv+M98DJkIJS3zgJ5wQdKxuzYxcqmRs22kgQL1op4P2punvHu82k8rPq1qM80exWxVPMh5DtD6IE+hgOwNL7Mg4R9OHIYrZBXMcJkWS2y+FAwi83EhxpGcpZ4ANhdxIddyloHjnoP9rOxwqoX7iSkuK9zAtVyBPzBwTzd+UUPVFJmcV1HuU0xyG5nvN0nm6m8WKhNowUKFBRqROCpe8rzZSCaPA2iRoFq5dYObNwBWleOF41ANYf4qJge3I1ZPBzoSkIXMS/X6Ifk037KJExRiG5kTnIUqpZ5WDxEQ10LkJ6WpmtbRqnWu0AA1vOF29cXjiyVbiKWgXDfTSUd9L2x6yfhu+Bg=
    file_glob: true
    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    skip_cleanup: true
    on:
      tags: true
      condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$DEPLOY_ARCH"
after_deploy:
- cd /home/travis/build/lukaspustina/rs-collector; cargo publish --token ${CRATES_IO_TOKEN}
