[package]
name = "rs-collector"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "An scollector compatible telemetry collector written in Rust"
repository = "https://github.com/lukaspustina/rs-collector.git"
documentation = "http://lukaspustina.github.io/rs-collector"
readme = "README.md"
license = "MIT"
keywords = ["bosun", "scollector", "command", "line", "metric"]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]

[[bin]]
name = "rs-scollector"
path = "src/main.rs"

[dependencies]
chan = "0.1.18"
chan-signal = "0.1.6"
clap = "2"
env_logger = "0.3"
log = "0.3"
toml = "0.1"

[dev-dependencies]
mktemp = "0.1.2"

